### ISSUE TITLE
Understanding annotations in DiagSet slides 

### ISSUE THREAD

**Issue by guillaumejaume** [michalkoziarski/DiagSet#1]
Hi, 

Thanks for making such a large dataset public!

I have a question regarding the slide-level annotations. When visualizing some slides and the corresponding annotations in https://ai-econsilio.diag.pl/tissue?tissue=S, I cannot understand the connection between the 2. For instance, in `00B4681B-C192-4219-B825-981364B31ED3`, the annotations provide information about 2 biopsies, where the actual image include 9. In some other ones, the annotations include information about more biospies than actually visible in the scan. 

Is it possible that there are mismatches between the two, or am I simply missing something here?

Thanks for your help,
Guillaume

**Comment by michalkoziarski** [comment]
Hi Guillaume,

thanks for expressing interest in the dataset!

Regarding your question: by slide-level annotations do you mean the text of the diagnosis (e.g., for the scan you give as an example, the one available at https://ai-econsilio.diag.pl/slide_info/00B4681B-C192-4219-B825-981364B31ED3)? In that case, the diagnosis is associated with whole patient examination, which is typically based on several different scans. To explain it on a specific example, the text of the diagnosis associated with that scan, that is:

_1. Prostate bioptates without cancer woven. 2. Prostate prostavo glandular cancer, Gleason 7 (3+ 4) index. Cancer dri is approximately 25% of the surface area of bioptates with a total length of 8 cm (it is present in 2 out of 4 bioptates)._

indicates that the examination was based on 2 different slides, in the first one histopathologist reported that there is no cancer present, and in the second one that it covers 25% of total valid tissue of the whole slide.

Unfortunately, due to the limitations of the original reporting system we do not have the information about which specific part of the diagnosis is associated with which slide. DiagSet-B.csv contains simplified record, in which we label overall presence of any cancerous tissue on the slide, but sadly this loses the information about specific Gleason grading and percentage of the tissue diagnosed as cancerous.

Hope it helps, feel free to ask more questions.

Best,
Michał

**Comment by guillaumejaume** [comment]
Hi Michal, 

Thanks for the information! 

It seems that the scans cannot be downloaded anymore. Are you aware of the issue? Downloading the patch DiagSet-A seems to work fine tough. 

Is there a way to rebuild the original scans from the DiagSetA patches?
If not, when can you have the scans back online?

Thank you so much for your help and the great work.
Guillaume

**Comment by michalkoziarski** [comment]
Hi Guillaume,

sorry for a long delay, FYI the issue should be fixed now. As I said in the other thread, in case of any further problems feel free to let me know, or alternatively let the site admin know - his contact info is available at https://ai-econsilio.diag.pl/contact, he might be able to address technical problems faster than me.

Best,
Michał
