### ISSUE TITLE
Diagset_B and Diagset_C

### ISSUE THREAD

**Issue by nelxnoemi** [michalkoziarski/DiagSet#5]
Hi, may i know if these datasets are available since i can't seems to find it in the website.

**Comment by michalkoziarski** [comment]
Yes, they should be available, due to the large size you can't download them as an archive (as .tgz files), but you can use the script provided at the website (https://ai-econsilio.diag.pl/download-script/; linked on the main page) to do it, which uses DiagSet-B.csv/DiagSet-C.csv files (also linked on the main page). Alternatively, you can manually browse the scans from https://ai-econsilio.diag.pl/annotated and download only the ones you are interested in (scan IDs match the content of .csv files).

**Comment by nelxnoemi** [comment]
ok can i know what does each of this label stands for is it:
BG: Background or Non-tissue region
T: Tumor
N: Normal or Non-tumor
A: Adipose tissue
R1, R2, R3, R4, R5: The Gleason graded

**Comment by michalkoziarski** [comment]
It's described in the paper:  "scan background (BG), tissue background (T), normal, healthy tissue (N), acquisition artifact (A), or one of the 1-5 Gleason grades (R1-R5)".
