### ISSUE TITLE
Is there a way to download the Diaset-A from a cmd command?

### ISSUE THREAD

**Issue by TanZheling** [michalkoziarski/DiagSet#7]
Hi, thank you for your great contributions! However, as the dataset is too large, I may need to download the dataset by command line on a server instead of on the website. I tried attach the cookies and the command copied from developer tools, but I still met permission issues. Is there a way to download the Diaset-A from a cmd command? Thank you!

**Comment by michalkoziarski** [comment]
Unfortunately I am not aware of any - I know that at one point it was possible, but possibly due to some unauthorized access attempts company hosting the data disabled it. Did you by any chance try to contact the website administrator (pawel.wasowicz@diag.pl)? He should know whether (and how) to do it.
